### ISSUE TITLE
base string not defined

### ISSUE THREAD

**Issue by akshaykumarvikram** [Deepomatic/deepomatic-client-python#2]
---------------------------------------------------------------------------
NameError                                 Traceback (most recent call last)
<ipython-input-6-b12ecb2c72bb> in <module>()
      1 
      2 
----> 3 client = deepomatic.Client(appID, apiKey)
      4 
      5 # ---------------------------------------------------------------------------------------------------

D:\Work\deepomatic-client-python-master\deepomatic\deepomatic.py in __init__(self, app_id, api_key, verify, host, version)
    246 
    247         if version is not None:
--> 248             if not isinstance(version, basestring):
    249                 version = 'v%g' % version
    250             elif version[0] != 'v':

NameError: name 'basestring' is not defined

**Comment by maingoh** [comment]
Thank you for the issue, this has been fixed. Everything should work in python3 now
