### ISSUE TITLE
Publish on pypi

### ISSUE THREAD

**Issue by maingoh** [Deepomatic/deepomatic-client-python#31]
Use twine 
https://blog.jetbrains.com/pycharm/2017/05/how-to-publish-your-package-on-pypi/

**Comment by thomas-riccardi** [comment]
We should read https://packaging.python.org/tutorials/packaging-projects/ to properly package everything.

**Comment by thomas-riccardi** [comment]
Maybe also do something about `universal`  wheel (python2 and python3).

**Comment by thomas-riccardi** [comment]
Maybe also pre-bump the next version on `master`.
