### ISSUE TITLE
Better `demo.py`

### ISSUE THREAD

**Issue by thomas-riccardi** [Deepomatic/deepomatic-client-python#35]
- [x] proper logging
- [x] log start and end for easier log human parsing
- [x] don't hardcode `/tmp`
- [x] better packaging (see #31 : do we want to install it via pypi as part of the lib? or as sample/example somewhere in the package)

**Comment by thomas-riccardi** [comment]
[ ] log debug to get `wait()` `GET /task` retry traces at least on automatic tests

**Comment by maingoh** [comment]
I am not in favor of including the demo in the package, I don't know any package that contains samples. 
I think a better readme/documentation eventually linking to the `demo.py` (outside the package sources).
